#!/usr/bin/env python3
"""Turn the nano-banana Softmax cog render into Cogmud's six seat sprites.

The source sheet (`scripts/art/source/cog_sheet.png`) is one render from
`gemini-2.5-flash-image` — the canonical Softmax cog, redrawn as a
market-town trader with a leather satchel and a travelling cloak, on a flat
chroma-green backdrop, with deliberately NEUTRAL grey plating so the tint can
carry the seat colour.

This script keys the backdrop, crops to the subject, pads to a square, resizes
to 128 px, then writes one tinted copy per seat colour into `data/`. Cogmud's
six seats are symmetric — there are no roles — so one cog kit in six tints is
the whole cast; the tint is what a spectator reads at board scale, which is why
the plating is neutral in the render and saturated here.

It OWNS these files, which are committed and never regenerated by CI:
    data/soldier_red_front.png      data/soldier_blue_front.png
    data/soldier_green_front.png    data/soldier_yellow_front.png
    data/soldier_violet_front.png   data/soldier_orange_front.png

The renderer's COLORS array is ["red","blue","green","yellow","violet",
"orange"] and its lookup is "soldier_" + color + "_front.png", so these names
are load-bearing.

    python3 scripts/art/make_cog_colors.py

Requires Pillow. Everything else in `data/` (arena_floor.png, font.ttf) is the
cogame-bullwhip starter's and is untouched.
"""

from __future__ import annotations

import colorsys
import pathlib
import sys

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "scripts" / "art" / "source" / "cog_sheet.png"
OUT_DIR = ROOT / "data"
SIZE = 128

# Hue (0..1) per seat colour, matching the renderer's COLOR_HEX table.
TINTS = {
    "red": 0.015,
    "blue": 0.585,
    "green": 0.345,
    "yellow": 0.135,
    "violet": 0.755,
    "orange": 0.075,
}

# Backdrop keying: the "pure green" a model returns is *some* green with a
# tinted edge, so key by distance from the median border colour rather than by
# an exact match.
KEY_TOLERANCE = 74


def border_median(image: Image.Image) -> tuple[int, int, int]:
    width, height = image.size
    pixels = image.load()
    samples = []
    for x in range(width):
        samples.append(pixels[x, 0][:3])
        samples.append(pixels[x, height - 1][:3])
    for y in range(height):
        samples.append(pixels[0, y][:3])
        samples.append(pixels[width - 1, y][:3])
    channels = []
    for index in range(3):
        values = sorted(sample[index] for sample in samples)
        channels.append(values[len(values) // 2])
    return tuple(channels)


def key_backdrop(image: Image.Image) -> Image.Image:
    """Flood-fill the backdrop from the border so green *inside* the cog (the
    cloak) survives."""
    image = image.convert("RGBA")
    width, height = image.size
    pixels = image.load()
    key = border_median(image)

    def is_key(x: int, y: int) -> bool:
        r, g, b, _ = pixels[x, y]
        return (abs(r - key[0]) + abs(g - key[1]) + abs(b - key[2])
                <= KEY_TOLERANCE)

    seen = bytearray(width * height)
    stack = []
    for x in range(width):
        stack.append((x, 0))
        stack.append((x, height - 1))
    for y in range(height):
        stack.append((0, y))
        stack.append((width - 1, y))
    while stack:
        x, y = stack.pop()
        if x < 0 or y < 0 or x >= width or y >= height:
            continue
        offset = y * width + x
        if seen[offset]:
            continue
        seen[offset] = 1
        if not is_key(x, y):
            continue
        pixels[x, y] = (0, 0, 0, 0)
        stack.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))
    return image


def crop_and_pad(image: Image.Image) -> Image.Image:
    box = image.getbbox()
    if box is None:
        raise SystemExit("the whole sheet keyed out; loosen KEY_TOLERANCE")
    cog = image.crop(box)
    side = max(cog.size)
    square = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    square.paste(cog, ((side - cog.width) // 2, (side - cog.height) // 2))
    return square.resize((SIZE, SIZE), Image.LANCZOS)


def tint(image: Image.Image, hue: float) -> Image.Image:
    """Re-hue everything but the cog's cyan eyes, and lift the saturation of
    the neutral plating so the seat colour reads at board scale."""
    out = image.copy()
    pixels = out.load()
    for y in range(out.height):
        for x in range(out.width):
            r, g, b, a = pixels[x, y]
            if a == 0:
                continue
            h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
            if 0.44 <= h <= 0.56 and s > 0.35:
                continue                      # the screen face stays cyan
            s = min(0.85, s * 0.5 + 0.42)
            # Lift the midtones a little: the render is dark and the sprite is
            # drawn over a light parchment card at ~40 px, where a muddy body
            # reads as a smudge rather than as a seat colour. Outlines (v very
            # low) are left alone so the silhouette stays crisp.
            if v > 0.10:
                v = min(1.0, v * 0.86 + 0.17)
            nr, ng, nb = colorsys.hsv_to_rgb(hue, s, v)
            pixels[x, y] = (int(nr * 255), int(ng * 255), int(nb * 255), a)
    return out


def main() -> int:
    if not SOURCE.exists():
        raise SystemExit(f"missing source render: {SOURCE}")
    base = crop_and_pad(key_backdrop(Image.open(SOURCE)))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for color, hue in TINTS.items():
        path = OUT_DIR / f"soldier_{color}_front.png"
        tint(base, hue).save(path)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
